version: "{build}"

os: Windows Server 2012
platform:
  - x64

environment:
  bundle_gemfile: test/integration/winrm/Gemfile

  matrix:
    - ruby_version: "193"
    - ruby_version: "200"
    - ruby_version: "21"
    - ruby_version: "22"

clone_folder: c:\projects\specinfra
clone_depth: 5
branches:
  only:
    - winrm_test_on_appveyor

cache:
  - C:\Ruby200\lib\ruby\gems\2.0.0
  - C:\Ruby200\bin

install:
  - ps: Enable-PSRemoting -Force
  - ps: Set-ExecutionPolicy RemoteSigned
  - winrm quickconfig -q
  - winrm set winrm/config/client @{TrustedHosts="*"}
  - winrm set winrm/config/client/auth @{Basic="true"}
  - winrm set winrm/config/service/auth @{Basic="true"}
  - winrm set winrm/config/service @{AllowUnencrypted="true"}
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - echo %PATH%
  - ruby --version
  - gem --version
  - gem install bundler --no-ri --no-rdoc

build_script:
  - bundle install 
  - netstat -a
  - net user
  - net localgroup
  - net user appveyor p@ssword55

test_script:
  - bundle exec rspec --backtrace -r .\test\integration\winrm\spec_helper.rb .\test\integration\winrm
